"""Turn the two result CSVs into `ml/synthetic/report.md`.

Includes the tutorial's own model-selection step, which is the part of the paper
most often skipped: "Identifying the Most Suitable Synthetic Data Set for a
Specific Use Case". Each run is ranked on every metric, and the ranks are
combined under two weight profiles taken verbatim from the paper's Table 3 --
profile A for supporting ML model development, profile B for education. A
smaller overall rank is better, and the two profiles disagree on purpose: they
encode genuinely different priorities about what synthetic data is *for*.
"""

from __future__ import annotations

import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent.parent
sys.path.insert(0, str(REPO_ROOT))

import numpy as np  # noqa: E402
import pandas as pd  # noqa: E402

from ml.synthetic.evaluate import LOWER_IS_BETTER  # noqa: E402

OUT_DIR = REPO_ROOT / "ml" / "synthetic"
QUALITY_CSV = OUT_DIR / "quality_by_checkpoint.csv"
AUGMENT_CSV = OUT_DIR / "augmentation.csv"
CONTROL_CSV = OUT_DIR / "privacy_control.csv"
PATIENTS_CSV = OUT_DIR / "patient_augmentation.csv"
REPORT_PATH = OUT_DIR / "report.md"

# The paper's Table 3, unaltered. Profile A supports ML model development and so
# weights prediction performance and feature importance; profile B supports
# education and so weights clinical knowledge violation and privacy instead.
WEIGHT_PROFILES: dict[str, dict[str, float]] = {
    "A (ML development)": {
        "dimension_wise_distance": 0.1,
        "column_wise_correlation": 0.1,
        "latent_cluster_analysis": 0.1,
        "medical_concept_abundance": 0.0,
        "clinical_knowledge_violation": 0.1,
        "tstr_auroc": 0.2,
        "feature_importance_overlap": 0.2,
        "membership_inference_f1": 0.1,
        "attribute_inference_f1": 0.1,
    },
    "B (education)": {
        "dimension_wise_distance": 0.1,
        "column_wise_correlation": 0.1,
        "latent_cluster_analysis": 0.0,
        "medical_concept_abundance": 0.0,
        "clinical_knowledge_violation": 0.4,
        "tstr_auroc": 0.0,
        "feature_importance_overlap": 0.0,
        "membership_inference_f1": 0.2,
        "attribute_inference_f1": 0.2,
    },
}

HEADER = """# Synthetic EHR generation with EMR-WGAN

> Generated by `ml/synthetic/run_tutorial.py`; regenerate with
> `python ml/synthetic/report.py`. Implements Yan C, Zhang Z, Nyemba S, Li Z.
> *Generating Synthetic Electronic Health Record Data Using Generative
> Adversarial Networks: Tutorial.* JMIR AI 2024;3:e52615
> ([doi:10.2196/52615](https://doi.org/10.2196/52615)) --
> `mimic-synthetic-generator-tutorial.pdf` in the repo root.

> This platform is validated on a 100-patient demo subset of MIMIC-IV. The
> engineering is real and the methodology is rigorous; the figures below
> demonstrate pipeline validity and do not transfer to clinical practice
> (PROJECT_PLAN.md section 17).
"""


def _best_checkpoint_per_run(quality: pd.DataFrame) -> pd.DataFrame:
    """One row per (paradigm, run): the checkpoint the paper's profile A prefers.

    The tutorial's reason for scoring checkpoints at all: "the model checkpoint
    that corresponds to the highest quality of the synthetic data is not
    necessarily the one with the lowest training loss", and "overtraining
    GAN-based models might degrade the quality of synthetic data".
    """
    scored = []
    for (paradigm, run), block in quality.groupby(["paradigm", "run"]):
        ranked = rank_metrics(block.reset_index(drop=True))
        weights = WEIGHT_PROFILES["A (ML development)"]
        overall = sum(
            ranked[metric] * weight for metric, weight in weights.items() if metric in ranked
        )
        chosen = block.reset_index(drop=True).iloc[int(np.asarray(overall).argmin())]
        scored.append({"paradigm": paradigm, "run": run, **chosen.to_dict()})
    return pd.DataFrame(scored)


def rank_metrics(frame: pd.DataFrame) -> pd.DataFrame:
    """Rank rows on each metric, 1 = best, honouring each metric's direction."""
    out = {}
    for metric, lower_better in LOWER_IS_BETTER.items():
        if metric not in frame.columns:
            continue
        series = frame[metric]
        if series.isna().all():
            continue
        # NaN ranks last regardless of direction: a generator that collapsed and
        # produced no measurable value should never win a ranking by default.
        out[metric] = series.rank(ascending=lower_better, na_option="bottom")
    return pd.DataFrame(out)


def rank_table(best: pd.DataFrame) -> pd.DataFrame:
    """The paper's Table 3: per-metric ranks plus both weighted overall rankings."""
    ranked = rank_metrics(best.reset_index(drop=True))
    table = ranked.copy()
    for name, weights in WEIGHT_PROFILES.items():
        table[f"overall {name}"] = sum(
            ranked[metric] * weight for metric, weight in weights.items() if metric in ranked
        )
    table.insert(0, "run", best["run"].to_numpy())
    table.insert(0, "paradigm", best["paradigm"].to_numpy())
    return table


def _privacy_section(quality: pd.DataFrame) -> str:
    """Membership-inference risk against the two anchors that make it readable.

    An F1 in isolation says nothing. The paper prints its own "Real" column for
    this reason -- what the same attack scores when you release the real data --
    and the chance floor is what it scores against a synthetic set unrelated to
    anyone. The generator's figure only means something between those two.
    """
    if "membership_inference_f1_real_baseline" not in quality.columns:
        return ""

    chance = float(quality["membership_inference_f1_chance"].iloc[0])
    released = float(quality["membership_inference_f1_real_baseline"].iloc[0])
    final = quality.loc[quality["epoch"] == quality["epoch"].max()]
    achieved = float(final["membership_inference_f1"].mean())
    span = released - chance
    position = (achieved - chance) / span if span else float("nan")

    table = pd.DataFrame(
        [
            {"scenario": "unrelated synthetic set (chance floor)", "membership F1": chance},
            {"scenario": "EMR-WGAN, final checkpoint (mean of 10 runs)", "membership F1": achieved},
            {"scenario": "releasing the real training data itself", "membership F1": released},
        ]
    )

    trend = quality.groupby("epoch")["membership_inference_f1"].mean().sort_index()
    direction = "rises" if trend.iloc[-1] > trend.iloc[0] else "falls"

    return (
        "\n### Privacy: the finding that does not transfer from the paper\n\n"
        + table.round(4).to_markdown(index=False)
        + f"\n\nThe generator sits **{position:.0%} of the way** from chance to the risk of "
        "simply publishing the real records. For comparison, the paper's five synthetic "
        "data sets score 0.29-0.31 against a real-data baseline of 0.91 -- their synthetic "
        "data substantially reduces disclosure risk, and this cohort's does not.\n\n"
        f"Risk also **{direction}** monotonically with training length "
        f"({trend.iloc[0]:.3f} at epoch {int(trend.index[0])} to {trend.iloc[-1]:.3f} at "
        f"epoch {int(trend.index[-1])}), which is the signature of memorisation rather "
        "than generalisation. This is the expected consequence of the scale gap: the "
        "paper fits 181,294 patients, this fits roughly 2,000 rows from 65 subjects, and "
        "a network with this much capacity on that little data reproduces its training "
        "set rather than the distribution behind it.\n\n"
        + _privacy_control()
        + "\n**Consequence: the synthetic cohort generated here must not be treated as "
        "de-identified and must not be shared outside the project.** That is the one use "
        "the tutorial's method exists to support, and it is the use this cohort cannot "
        "safely make of it.\n"
    )


def _privacy_control() -> str:
    """The swap test from `privacy_control.py`, which rules out the obvious confound."""
    if not CONTROL_CSV.exists():
        return ""
    control = pd.read_csv(CONTROL_CSV)
    column = "attack scores A as members"
    on_a = float(control.loc[control["generator fitted on"] == "A", column].iloc[0])
    on_b = float(control.loc[control["generator fitted on"] == "B", column].iloc[0])
    return (
        "\n**The confound is ruled out.** A membership figure this high could mean the "
        "attack is reading a fixed difference between the two subject groups rather than "
        "anything the generator memorised, so `privacy_control.py` refits the generator on "
        "the *held-out* group and re-runs the identical attack against the identical "
        "targets:\n\n"
        + control.round(4).to_markdown(index=False)
        + f"\n\nGroup A is identified as the training set at **{on_a:.3f}** by a generator "
        f"that saw A, and at **{on_b:.3f}** by one that saw B instead -- a swing of "
        f"{on_a - on_b:+.3f} on the same targets. The verdict follows the generator's "
        "training set, which is memorisation and not a cohort artefact.\n"
    )


def _fmt(frame: pd.DataFrame, digits: int = 4) -> str:
    return frame.round(digits).to_markdown(index=False)


def build_report() -> str:
    quality = pd.read_csv(QUALITY_CSV)
    augment = pd.read_csv(AUGMENT_CSV)
    parts = [HEADER]

    # --- Stage 1 ------------------------------------------------------------
    parts.append("\n## 1. Data quality across runs and checkpoints\n")
    parts.append(
        "Five independent EMR-WGAN runs per training paradigm, each checkpointed "
        "along its trajectory and scored on the tutorial's full battery. The "
        "generator sees 70% of subjects; every figure here is measured against "
        "the held-out 30%.\n"
    )

    trajectory = (
        quality.groupby(["paradigm", "epoch"])[
            [
                "dimension_wise_distance",
                "column_wise_correlation",
                "latent_cluster_analysis",
                "clinical_knowledge_violation",
                "temporal_coherence",
                "tstr_auroc",
                "synthetic_positive_rate",
            ]
        ]
        .mean()
        .reset_index()
    )
    parts.append("\n### Trajectory, averaged over the five runs\n")
    parts.append(_fmt(trajectory))
    parts.append(
        "\n\nThe tutorial's warning about training length is visible here: quality "
        "on these metrics does not improve monotonically with epochs, which is why "
        "checkpoints are scored rather than the final weights trusted.\n"
    )

    # --- The minority-label finding -----------------------------------------
    rates = quality.groupby("paradigm")[["synthetic_positive_rate", "real_positive_rate"]].mean()
    parts.append("\n### The minority label, and why conditional training is not optional\n")
    parts.append(_fmt(rates.reset_index()))
    # Indexed column-then-label rather than `.loc[label, column]`: the latter
    # is typed as a Scalar union wide enough to include str and datetime, which
    # float() will not accept.
    non = float(rates["synthetic_positive_rate"].loc["nonconditional"])
    real = float(rates["real_positive_rate"].loc["nonconditional"])
    by_epoch = (
        quality.loc[quality["paradigm"] == "nonconditional"]
        .groupby("epoch")["synthetic_positive_rate"]
        .mean()
        .sort_index()
    )
    worst_epoch = int(by_epoch.idxmin())
    worst = float(by_epoch.min())
    parts.append(
        f"\n\nThe nonconditional generator -- the paradigm the tutorial demonstrates -- "
        f"averages **{non:.4f}** positives against a real rate of **{real:.4f}**, and the "
        f"average hides the real problem. Early in training it collapses the class "
        f"almost entirely: **{worst:.4f}** at epoch {worst_epoch}, roughly "
        f"{real / max(worst, 1e-9):.0f}x under-represented, which leaves too few positives "
        "to fit a classifier on at all. Even at its best it never reliably holds the rate, "
        "because nothing in the objective requires it to.\n\n"
        "This is the failure the tutorial predicts for low-prevalence concepts: generative "
        'models "cannot accurately capture the statistical properties of these variables '
        '... due to the limited observations in the data set". At a 4% base rate in 2,979 '
        "rows the outcome *is* a low-prevalence concept.\n\n"
        "The conditional paradigm holds the rate exactly, because the label is an input "
        "rather than something the generator has to learn to emit. That is the tutorial's "
        'own remedy -- conditional training "enables the control over the categories of '
        'the generated data in terms of the label variables" -- and stage 2 uses it '
        "throughout.\n"
    )

    # --- Paper's Table 3 ----------------------------------------------------
    best = _best_checkpoint_per_run(quality)
    parts.append("\n### Best checkpoint per run, and the paper's use-case ranking\n")
    display = best[
        [
            "paradigm",
            "run",
            "epoch",
            "dimension_wise_distance",
            "column_wise_correlation",
            "latent_cluster_analysis",
            "clinical_knowledge_violation",
            "temporal_coherence",
            "tstr_auroc",
            "feature_importance_overlap",
            "membership_inference_f1",
            "attribute_inference_f1",
        ]
    ]
    parts.append(_fmt(display))
    parts.append("\n\n**Ranked** (1 = best on that metric; lower overall is better):\n\n")
    parts.append(_fmt(rank_table(best), digits=2))

    trtr = float(quality["trtr_auroc"].iloc[0])
    parts.append(
        f"\n\nTrain-on-real/test-on-real (TRTR) AUROC on the same held-out subjects is "
        f"**{trtr:.4f}**; every TSTR figure above should be read against it.\n"
    )

    parts.append(_privacy_section(quality))

    # --- Stage 2 ------------------------------------------------------------
    parts.append("\n## 2. Does synthetic data improve the model?\n")
    parts.append(
        "Subject-grouped 5-fold CV. In every fold the generator is refitted on that "
        "fold's training subjects only, and all three arms are scored on the same "
        "**real** held-out subjects. AUPRC is the metric this project judges on, at a "
        "4% base rate.\n"
    )

    pivot = (
        augment.groupby(["arm", "composition", "k"])[["auprc", "auroc"]]
        .mean()
        .reset_index()
        .sort_values(["arm", "composition", "k"])
    )
    parts.append("\n")
    parts.append(_fmt(pivot))

    key = ["repeat", "fold"]
    baseline = augment.loc[augment["arm"] == "trtr"].set_index(key)["auprc"]
    lines = []
    for (composition, k), block in augment.loc[augment["arm"] == "augmented"].groupby(
        ["composition", "k"]
    ):
        paired = block.set_index(key)["auprc"].reindex(baseline.index)
        comparable = paired.notna()
        delta = float((paired - baseline)[comparable].mean())
        wins = int((paired > baseline)[comparable].sum())
        total = int(comparable.sum())
        lines.append(
            {
                "composition": composition,
                "k": k,
                "mean delta vs TRTR": delta,
                "paired wins": f"{wins}/{total}",
                "meets 15/20 bar": "yes" if total and wins / total >= 0.75 else "no",
            }
        )
    parts.append("\n\n### Augmented against the real-only baseline, paired by (repeat, fold)\n\n")
    parts.append(_fmt(pd.DataFrame(lines)))
    parts.append(
        "\n\nThe win-rate bar is this project's existing one: a change is called real "
        "when it wins at least 15 of 20 paired repeats (`ml/evaluation/report.md`). "
        "Winning about half of them is what a coin flip looks like.\n"
    )

    mean_width = float(
        (
            augment.loc[augment["arm"] == "trtr", "auprc_hi"]
            - augment.loc[augment["arm"] == "trtr", "auprc_lo"]
        ).mean()
    )
    parts.append(
        f"\n\nThe baseline's own bootstrap CI averages **{mean_width:.3f}** wide across "
        "folds. Any delta well inside that width is not a result, whatever its sign -- "
        "it is the noise floor of a cohort with 49 positive subjects.\n"
    )

    parts.append(_patient_section())
    parts.append(_conclusion(augment, quality))
    return "".join(parts)


def _patient_section() -> str:
    """Whole synthetic patients, class-balanced -- the objection to section 2."""
    if not PATIENTS_CSV.exists():
        return ""
    frame = pd.read_csv(PATIENTS_CSV)
    if frame.empty:
        return ""

    key = ["repeat", "fold"]
    baseline = frame.loc[frame["arm"] == "real"].set_index(key)["auprc"]
    lines: list[dict[str, object]] = []
    # The largest arm's figures are tracked as typed scalars while the table is
    # built rather than dug back out of `lines` afterwards -- the row dicts hold a
    # str/int/float union, so `max(lines, key=...)` and the arithmetic on what it
    # returns are both untypeable without a cast that would only be hiding this.
    biggest_subjects = 0.0
    biggest_delta = 0.0
    biggest_wins = ""
    for k, block in frame.loc[frame["arm"] == "balanced"].groupby("k"):
        paired = block.set_index(key)["auprc"].reindex(baseline.index)
        mask = paired.notna()
        wins = int((paired > baseline)[mask].sum())
        total = int(mask.sum())
        subjects = float(block["n_positive_subjects"].mean())
        delta = float((paired - baseline)[mask].mean())
        lines.append(
            {
                "synthetic patients per real one": k,
                "positive subjects": round(subjects),
                "mean AUPRC": float(block["auprc"].mean()),
                "delta vs real-only": delta,
                "paired wins": f"{wins}/{total}",
                "meets 15/20 bar": "yes" if total and wins / total >= 0.75 else "no",
            }
        )
        if subjects > biggest_subjects:
            biggest_subjects, biggest_delta, biggest_wins = subjects, delta, f"{wins}/{total}"

    real_subjects = round(float(baseline_subjects(frame)))
    widths = frame.assign(width=frame["auprc_hi"] - frame["auprc_lo"])
    ci_real = float(widths.loc[widths["arm"] == "real", "width"].mean())
    ci_big = float(widths.loc[widths["k"] == widths["k"].max(), "width"].mean())

    return (
        "\n## 3. Whole synthetic patients, class-balanced\n\n"
        "Section 2 generates patient-*hours*: rows with no identity, no trajectory, "
        "and no way to raise the count of positive **subjects** -- which is the "
        "quantity [`reliability.py`](../evaluation/reliability.py) identifies as "
        "binding, at 49 against the ~725 a 0.10-wide AUPRC interval would need. "
        "The fair objection is that patient-hours are not patients.\n\n"
        "[`patients.py`](patients.py) removes the objection. Each synthetic patient "
        "gets a length of stay, an hourly trajectory across nine vitals, static "
        "attributes, an event time if it deteriorates, and its own subject id, "
        "generated 50/50 by class. Derived features are **recomputed** from the "
        "generated trajectory by the same `engineer.add_rolling_features` the real "
        "pipeline uses, so a synthetic patient's `hr_4h_std` describes its own heart "
        "rate rather than being an independently generated column.\n\n"
        f"Baseline: **{real_subjects} positive subjects** per training fold.\n\n"
        + pd.DataFrame(lines).round(4).to_markdown(index=False)
        + "\n\n**The positive-subject count is no longer the constraint, and nothing "
        f"improves.** The largest arm manufactures **{round(biggest_subjects)} "
        f"positive subjects** -- {biggest_subjects / max(real_subjects, 1):.0f}x "
        "the real count -- and AUPRC is "
        f"{biggest_delta:+.4f} against the real-only baseline, winning "
        f"{biggest_wins} paired comparisons. No arm clears the 15/20 bar; the "
        "best is 9/20, which is a coin flip.\n\n"
        f"The confidence interval does not move either: {ci_real:.3f} wide on the "
        f"real-only arm against {ci_big:.3f} at the largest synthetic multiplier. That "
        "is the *correct* behaviour and worth stating plainly, because it is easy to "
        "misread as a failure. The interval is measured on real held-out patients, and "
        "synthetic patients never enter a test fold, so nothing about the training side "
        "can narrow it. An interval that *did* tighten here would be the warning sign -- "
        "it would mean synthetic rows had reached the evaluation, which is exactly the "
        "manufactured precision "
        "[`synthetic_ceiling_report.md`](../evaluation/synthetic_ceiling_report.md) "
        "measures. What the reliability analysis asks for is ~725 positive subjects "
        "*observed*, which is a statement about how many real patients the cohort "
        "contains, and no generator changes that number.\n\n"
        "This is the cleanest statement of the result in the whole report. A synthetic "
        "positive subject is not a positive subject. The count went up more than "
        "tenfold and bought nothing, because all of it was derived from the same 39 "
        "real positive subjects the generator was fitted to -- and no amount of "
        "resampling an estimate tells you about the patients that estimate never "
        "saw.\n"
    )


def baseline_subjects(frame: pd.DataFrame) -> float:
    """Mean positive-subject count in the real-only arm."""
    return float(frame.loc[frame["arm"] == "real", "n_positive_subjects"].mean())


def _conclusion(augment: pd.DataFrame, quality: pd.DataFrame) -> str:
    """What the two stages jointly establish."""
    key = ["repeat", "fold"]
    baseline = augment.loc[augment["arm"] == "trtr"].set_index(key)["auprc"]
    best_delta, best_arm, best_wins, total = -np.inf, "", 0, 0
    for (composition, k), block in augment.loc[augment["arm"] == "augmented"].groupby(
        ["composition", "k"]
    ):
        paired = block.set_index(key)["auprc"].reindex(baseline.index)
        mask = paired.notna()
        delta = float((paired - baseline)[mask].mean())
        if delta > best_delta:
            best_delta = delta
            best_arm = f"{composition}, k={k}"
            best_wins = int((paired > baseline)[mask].sum())
            total = int(mask.sum())

    final = quality.loc[quality["epoch"] == quality["epoch"].max()]
    dwd = float(final["dimension_wise_distance"].mean())
    tstr = float(final["tstr_auroc"].mean())
    trtr = float(quality["trtr_auroc"].iloc[0])

    return (
        "\n## 4. What this establishes\n\n"
        f"**The generator works.** Dimension-wise distance reaches {dwd:.2f}, inside the "
        "0.52-1.56 band the paper reports for its own five runs on 181,294 patients, and a "
        f"model trained purely on synthetic rows scores AUROC {tstr:.3f} against the real "
        f"model's {trtr:.3f} on the same held-out patients. This is not a broken "
        "implementation producing a null result.\n\n"
        "**It still does not buy the thing it was reached for.** Not one augmented arm "
        f"beats the real-only baseline: the best of six is {best_arm} at "
        f"{best_delta:+.4f} AUPRC, winning {best_wins} of {total} paired comparisons "
        "against a bar of 15. The largest synthetic multiplier is the *worst* arm, which "
        "is the direction to expect if synthetic rows add distribution shift rather than "
        "information. Section 3 makes the same point at the patient level, where the "
        "positive-subject count rises more than tenfold and AUPRC still does not.\n\n"
        "This settles the question "
        "[`synthetic_ceiling_report.md`](../evaluation/synthetic_ceiling_report.md) left "
        "open. That report measured a resampling generator and could only reach 100% or 0% "
        "fidelity, never the middle, so it could not rule out that a *real* generator at "
        "intermediate fidelity would behave differently. One does now exist, it sits in "
        "that band, and it behaves the same way. The constraint was never fidelity. A "
        "generator fitted on 74 training subjects is an estimate of a distribution, and "
        "sampling an estimate does not add information about the population behind it -- "
        "which is why the honest lever on this project's confidence interval remains more "
        "real patients (`warehouse/fetch_mimic4.py`), not more rows.\n\n"
        "**The privacy result is the one that changes what may be done with the output.** "
        "The tutorial's method exists to make data shareable; on this cohort it produces "
        "records that an adversary can trace back to their training subjects at two-thirds "
        "of the risk of publishing the real data outright. The synthetic cohort is "
        "therefore usable *inside* the project for the purposes "
        "[`README.md`](README.md) lists, and is not publishable.\n"
    )


def main() -> None:
    REPORT_PATH.write_text(build_report())
    print(f"wrote {REPORT_PATH}")


if __name__ == "__main__":
    main()
